create database customer_behavior;

use  customer_behavior;

SELECT * FROM customer;

SELECT TOP  10 * FROM dbo.customer;

--1. Total revenue generated by male vs. female customers?
SELECT gender,sum(purchase_amount) AS revenue 
FROM customer 
GROUP BY gender

--2. Which customers used a  discount but still  spent most than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied='Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

--3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND(CAST(AVG(review_rating)as numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC;

--4. Compare the average Purchase Amount between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2) AS "Average Purchase Amount"
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

--5. Do suscribed customers spend more? Compare average spend and total revenue between suscribers and non-suscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(sum(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY  total_revenue, avg_spend DESC;

--6. Which 5 products  have the highest  percentage of puchases with discount applied?
SELECT top 5 item_purchased,
ROUND(SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2 ) AS discount_rate
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--7. Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment.
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE
    WHEN previous_purchases =1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN  'Returning'
     ELSE 'Loyal'
     END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(customer_id) AS total_customers
FROM customer_type
GROUP BY customer_segment;

--8. What are the top 3 most purchased product with each category?
WITH item_counts AS(
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() over(partition by category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer 
GROUP BY category, item_purchased
)
SELECT item_rank ,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank<=3;

--9. Are customer who are repeat buyers(more than 5  previous purchases ) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer 
WHERE previous_purchases>5
GROUP BY subscription_status 

--10. What are revenue contribution  of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
from customer  
GROUP BY age_group 
ORDER BY  total_revenue DESC;

--11. Who are the top 10 customers based on total spending?
SELECT TOP 10 customer_id,
    sum(purchase_amount) AS total_spent
FROM customer
GROUP BY customer_id
ORDER BY total_spent DESC;

--12. Do discounts influence customer spending behavior?
SELECT
    discount_applied,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY discount_applied;

--13. Which product categories generate the highest revenue?
SELECT   category,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;

--14. Which age group has the highest average spending per purchase?
SELECT
    age_group,
    ROUND(AVG(purchase_amount),2) AS avg_spending
FROM customer
GROUP BY age_group
ORDER BY avg_spending DESC;

